Auto-detect wxwigets
Change-Id: I9f9140ed187cd82517481df95c5c98eebffa51a0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -250,6 +250,7 @@ HAVE_LIST="
     aom_ports
     pthread_h
     unistd_h
+    wxwidgets
 "
 EXPERIMENT_LIST="
     fp_mb_stats
@@ -630,6 +631,12 @@ EOF
     check_header unistd.h # for sysconf(3) and friends.
 
     check_header aom/aom_integer.h -I${source_path} && enable_feature aom_ports
+    enabled analyzer && soft_enable wxwidgets
+    if enabled wxwidgets; then
+      hash wx-config 2>&- || die "Couldn't find wx-config"
+      WX_CXXFLAGS=$(wx-config --cppflags)
+      WX_LDFLAGS=$(wx-config --libs)
+    fi
 }
 
 process_toolchain() {
